food = input("Food: ")
name = input("Name: ")
adjective = input("Adjective: ")
noun = input("Noun: ")
verb1 = input("Verb 1: ")
verb2 = input("Verb 2: ")
verb3 = input("Verb 3: ")
print(f"It was {food} day at school, and {name} was super {adjective} for lunch. But when she went outside to eat, a {noun} stole her {food}! {name} chased the {noun} all over school. She {verb1}, {verb2}, and {verb3} through the playground. Then she tripped on her {noun} and the {noun} escaped! Luckily, {name}’s friends were willing to share their {food} with her.")